/**
 * MODULE — JARVIS-style auto-plan extraction.
 *
 * Turns a raw agent chat/tool log into a PROJECT_PLAN.md checklist: Winnow
 * compacts the log first (reused from context-compactor.ts, zero new
 * concept), a System-2 LLM call extracts completed/pending tasks from the
 * compacted text (same chatJson + deterministic-offline-fallback pattern as
 * jev-planner.ts), then pending tasks are prioritized with one batched
 * Score pass.
 */

import { System2Client } from "../core/llm.js";
import type { JevBackend, ScoreResult } from "../core/types.js";
import type { JarvisAutoPlanReport } from "../core/module-types.js";
import type { ContextCompactor } from "./context-compactor.js";

export interface JarvisAutoPlanDeps {
  backend: JevBackend;
  llm: System2Client;
  compactor: ContextCompactor;
}

interface ExtractedTasksDraft {
  completed: string[];
  pending: string[];
}

function offlineExtract(text: string): ExtractedTasksDraft {
  const completed: string[] = [];
  const pending: string[] = [];
  for (const raw of text.split(/\r?\n/)) {
    const line = raw.trim();
    if (!line) continue;
    if (/^-\s*\[x\]/i.test(line)) completed.push(line.replace(/^-\s*\[x\]\s*/i, ""));
    else if (/^-\s*\[ \]/.test(line)) pending.push(line.replace(/^-\s*\[ \]\s*/, ""));
    else if (/\bTODO\b|\bFIXME\b|\bnext:\s/i.test(line)) pending.push(line);
    else if (/\b(?:done|fixed|completed|shipped)\b/i.test(line) && line.length < 200) completed.push(line);
  }
  return { completed: completed.slice(0, 20), pending: pending.slice(0, 20) };
}

export class JarvisAutoPlan {
  constructor(private readonly deps: JarvisAutoPlanDeps) {}

  async extract(logText: string, opts: { goal?: string } = {}): Promise<JarvisAutoPlanReport> {
    const started = Date.now();
    const goal = opts.goal ?? "extract completed vs pending engineering tasks";
    const compaction = await this.deps.compactor.winnow(logText, { goal });

    const draft = await this.deps.llm.chatJson<ExtractedTasksDraft>(
      [
        { role: "system", content: "You extract a task list from an engineering log. Reply with one JSON object only." },
        {
          role: "user",
          content:
            `Log (already Winnow-compacted, structure preserved verbatim):\n${compaction.compacted.slice(0, 12000)}\n\n` +
            `Reply as {"completed": string[], "pending": string[]} — short, concrete task phrases, no commentary.`,
        },
      ],
      () => offlineExtract(compaction.compacted),
    );

    const pendingTexts = draft.value.pending.slice(0, 20);
    const priorities = pendingTexts.length
      ? ((await this.deps.backend.batch(
          pendingTexts.map((text) => ({
            kind: "score" as const,
            question: "Priority of this pending task on a 1-10 scale (10 = urgent/blocking).",
            min: 1,
            max: 10,
            state: text,
          })),
        )) as ScoreResult[])
      : [];

    const pending = pendingTexts
      .map((text, i) => ({ text, priority: priorities[i]! }))
      .sort((a, b) => b.priority.score - a.priority.score);

    return {
      completed: draft.value.completed.slice(0, 20),
      pending,
      source: draft.source === "llm" ? "llm" : "offline-fallback",
      compaction: { bytesIn: compaction.bytesIn, bytesOut: compaction.bytesOut, keptLines: compaction.keptLines },
      latencyMs: Date.now() - started,
    };
  }

  toMarkdownLines(report: JarvisAutoPlanReport, title = "Project Plan"): string[] {
    const lines = [`# ${title}`, "", `_Auto-generated by jev_jarvis_auto_plan — source: ${report.source}_`, "", "## Pending"];
    if (report.pending.length === 0) lines.push("_Nothing pending._");
    for (const p of report.pending) lines.push(`- [ ] ${p.text} (priority ${p.priority.score}/10)`);
    lines.push("", "## Completed");
    if (report.completed.length === 0) lines.push("_Nothing completed yet._");
    for (const c of report.completed) lines.push(`- [x] ${c}`);
    return lines;
  }
}
